/// Flutter icons Almiya
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Almiya
///      fonts:
///       - asset: fonts/Almiya.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Almiya {
  Almiya._();

  static const _kFontFam = 'Almiya';
  static const String _kFontPkg = null;

  static const IconData face = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asterisk = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connect = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
