/// Flutter icons Almiya
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Almiya
///      fonts:
///       - asset: fonts/Almiya.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Almiya {
  Almiya._();

  static const _kFontFam = 'Almiya';
  static const String _kFontPkg = null;

  static const IconData face = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
